// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYQ3LptsRPWmVWaYEVhvEtBLC4e0tA9o8',
    appId: '1:632365486882:web:4ebdd0cf437ed3372f0b7b',
    messagingSenderId: '632365486882',
    projectId: 'fir-solaire',
    authDomain: 'fir-solaire.firebaseapp.com',
    storageBucket: 'fir-solaire.firebasestorage.app',
    measurementId: 'G-8TKB7L7SSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ3OTWX61EMq5DwD_DpUipA3f33tymNPQ',
    appId: '1:632365486882:android:0ada4e5050fd544a2f0b7b',
    messagingSenderId: '632365486882',
    projectId: 'fir-solaire',
    storageBucket: 'fir-solaire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoUSDEBwLIOcbNt17Q5p8bUsx7nK5J1oU',
    appId: '1:632365486882:ios:f2b108e18b7449a12f0b7b',
    messagingSenderId: '632365486882',
    projectId: 'fir-solaire',
    storageBucket: 'fir-solaire.firebasestorage.app',
    iosBundleId: 'com.example.systemSolaire',
  );
}
